"""
Activity Extraction, Aggregation and Visualization.

This module retrieves activity logs stored in PostgreSQL under the
`variable_log_float` table, aggregates them per hour and per day,
constructs a pivot table, and visualizes both the tabular data and
daily activity trends.

The activity logs contain timestamped numeric values, where each row
represents a recorded event or measurement generated by the machine.

This module performs:
- Time conversion from human-readable timestamps to epoch milliseconds.
- SQL extraction of hourly log counts within a selected date interval.
- Pivot transformation into a day × hour activity matrix.
- Visualization of the activity table using matplotlib.
- Multi-day line plotting to detect patterns such as machine uptime,
  downtime, and general activity level variations.

Data Outputs
------------
pivot_table :
    A matrix where rows represent hours (0–23), columns represent
    individual days, and each cell contains the number of logged
    entries for that hour and date.

Line Plot :
    A multi-day activity curve showing how many log entries were
    generated each hour for every day in the selected interval.

Functions
---------
load_db_config :
    Load database connection settings from config.yaml.
create_engine_from_config :
    Create SQLAlchemy engine from configuration dictionary.
convert_timestamp_to_epoch_ms :
    Convert human-readable timestamps to epoch milliseconds.
fetch_activity_data :
    Retrieve log-entry counts per hour over the selected date range.
build_pivot_table :
    Convert raw hourly data into a structured day × hour matrix.
display_pivot_table :
    Render the pivot table visually using matplotlib.
plot_activity_trends :
    Plot hourly activity curves for multiple days.
"""


import matplotlib.pyplot as plt
import pandas as pd
from sqlalchemy import create_engine, text
import yaml

# --- 1. Load configuration file ---
with open("config.yaml", "r") as f:
    config = yaml.safe_load(f)

db = config["database"]

engine = create_engine(
    f"postgresql+psycopg2://{db['user']}:{db['password']}@{db['host']}:{db['port']}/{db['dbname']}"
)

# --- 2. Date interval ---
date_start = "2021-01-10"
date_end   = "2021-01-15"

start_ts = f"{date_start} 00:00:00"
end_ts   = f"{date_end} 23:59:59"

# --- 3. Convert timestamps to epoch milliseconds ---
epoch_query = text("SELECT extract(epoch FROM timestamp :t) AS s")
with engine.connect() as conn:
    start_ms = int(conn.execute(epoch_query, {"t": start_ts}).scalar() * 1000)
    end_ms   = int(conn.execute(epoch_query, {"t": end_ts}).scalar() * 1000)

# --- 4. SQL: fetch log rows per hour and day ---
q = text("""
    SELECT
        DATE(to_timestamp(date/1000)) AS day,
        EXTRACT(HOUR FROM to_timestamp(date/1000)) AS hour,
        COUNT(*) AS log_count
    FROM public.variable_log_float
    WHERE date BETWEEN :start_ms AND :end_ms
    GROUP BY day, hour
    ORDER BY day, hour;
""")

with engine.connect() as conn:
    df = pd.read_sql(q, conn, params={"start_ms": start_ms, "end_ms": end_ms})

if df.empty:
    print("No data found.")
    exit()

df["hour"] = df["hour"].astype(int)

# --- 5. Create pivot table (hours × days) ---
pivot_table = df.pivot(index="hour", columns="day", values="log_count").fillna(0)

# --- 6. DISPLAY THE TABLE using matplotlib.table ---
fig, ax = plt.subplots(figsize=(14, 7))
ax.axis('off')

tbl = ax.table(
    cellText=pivot_table.values,
    rowLabels=pivot_table.index,
    colLabels=pivot_table.columns,
    loc='center',
    cellLoc='center'
)

tbl.auto_set_font_size(False)
tbl.set_fontsize(8)
tbl.scale(1.2, 1.4)

plt.title(f"Activity Table (logged rows per hour) – {date_start} to {date_end}", fontsize=14)
plt.show()

# --- 7. PLOT – Line chart across multiple days ---
plt.figure(figsize=(15, 8))
plt.style.use("seaborn-v0_8")

for day in pivot_table.columns:
    plt.plot(
        pivot_table.index,
        pivot_table[day],
        marker="o",
        linewidth=2,
        label=str(day)
    )

plt.title(f"Activity per Hour – {date_start} to {date_end}", fontsize=16)
plt.xlabel("Hour of Day (0–23)", fontsize=13)
plt.ylabel("Number of Logged Rows", fontsize=13)
plt.xticks(range(24))
plt.grid(True, linestyle="--", alpha=0.5)
plt.legend(title="Date")
plt.tight_layout()
plt.subplots_adjust(top=0.5)
plt.show()
